package defpackage;

import com.itextpdf.text.pdf.a;
import java.lang.reflect.Field;
import java.util.HashMap;
import java.util.Map;
import org.apache.http.HttpHeaders;

/* renamed from: h70  reason: default package */
public class h70 extends o70 implements Comparable<h70> {
    public static final h70 A = new h70("Alt");
    public static final h70 A0 = new h70("ByteRange");
    public static final h70 A1 = new h70("Configuration");
    public static final h70 A2 = new h70("Div");
    public static final h70 A3 = new h70("FDecodeParms");
    public static final h70 A4 = new h70("GCS");
    public static final h70 A5 = new h70("ImageMask");
    public static final h70 A6 = new h70("LowerAlpha");
    public static final h70 A7 = new h70("NumCopies");
    public static final h70 A8 = new h70("PatternType");
    public static final h70 A9 = new h70("RC");
    public static final h70 Aa = new h70("Separation");
    public static final h70 Ab = new h70("TA");
    public static final h70 Ac = new h70("Tx");
    public static final h70 Ad = new h70("Width");
    public static final h70 B = new h70("Alternate");
    public static final h70 B0 = new h70("C");
    public static final h70 B1 = new h70("Configurations");
    public static final h70 B2 = new h70("DL");
    public static final h70 B3 = new h70("FDF");
    public static final h70 B4 = new h70("GEO");
    public static final h70 B5 = new h70("Include");
    public static final h70 B6 = new h70("LowerRoman");
    public static final h70 B7 = new h70("Nums");
    public static final h70 B8 = new h70("pb");
    public static final h70 B9 = new h70("RD");
    public static final h70 Ba = new h70("SetOCGState");
    public static final h70 Bb = new h70("Table");
    public static final h70 Bc = new h70("Type");
    public static final h70 Bd = new h70("Widths");
    public static final h70 C = new h70("AlternatePresentations");
    public static final h70 C0 = new h70("C0");
    public static final h70 C1 = new h70("ContactInfo");
    public static final h70 C2 = new h70("Dm");
    public static final h70 C3 = new h70("Ff");
    public static final h70 C4 = new h70("GEOGCS");
    public static final h70 C5 = new h70("Ind");
    public static final h70 C6 = new h70("LPTS");
    public static final h70 C7 = new h70("O");
    public static final h70 C8 = new h70("PC");
    public static final h70 C9 = new h70("Reason");
    public static final h70 Ca = new h70("Settings");
    public static final h70 Cb = new h70("Tabs");
    public static final h70 Cc = new h70("Type0");
    public static final h70 Cd = new h70("Win");
    public static final h70 D = new h70("Alternates");
    public static final h70 D0 = new h70("C1");
    public static final h70 D1 = new h70("Content");
    public static final h70 D2 = new h70("DocMDP");
    public static final h70 D3 = new h70("FFilter");
    public static final h70 D4 = new h70("Glitter");
    public static final h70 D5 = new h70("Index");
    public static final h70 D6 = new h70("LZWDecode");
    public static final h70 D7 = new h70("Obj");
    public static final h70 D8 = new h70("PDF");
    public static final h70 D9 = new h70("Recipients");
    public static final h70 Da = new h70("Shading");
    public static final h70 Db = new h70("TBody");
    public static final h70 Dc = new h70("Type1");
    public static final h70 Dd = new h70("WinAnsiEncoding");
    public static final h70 E = new h70("And");
    public static final h70 E0 = new h70("CA");
    public static final h70 E1 = new h70("Contents");
    public static final h70 E2 = new h70("DocOpen");
    public static final h70 E3 = new h70("FG");
    public static final h70 E4 = new h70("GoTo");
    public static final h70 E5 = new h70("Indexed");
    public static final h70 E6 = new h70("M");
    public static final h70 E7 = new h70("OBJR");
    public static final h70 E8 = new h70("PDFDocEncoding");
    public static final h70 E9 = new h70("Rect");
    public static final h70 Ea = new h70("ShadingType");
    public static final h70 Eb = new h70("TD");
    public static final h70 Ec = new h70("Type3");
    public static final h70 Ed = new h70("Window");
    public static final h70 F = new h70("Animation");
    public static final h70 F0 = new h70("ca");
    public static final h70 F1 = new h70("Coords");
    public static final h70 F2 = new h70("DocTimeStamp");
    public static final h70 F3 = new h70("FieldMDP");
    public static final h70 F4 = new h70("GoTo3DView");
    public static final h70 F5 = new h70("Info");
    public static final h70 F6 = new h70("Mac");
    public static final h70 F7 = new h70("ObjStm");
    public static final h70 F8 = new h70("PDU");
    public static final h70 F9 = new h70("Redact");
    public static final h70 Fa = new h70("Shift-JIS");
    public static final h70 Fb = new h70("TR");
    public static final h70 Fc = new h70("U");
    public static final h70 Fd = new h70("Windowed");
    public static final h70 G = new h70("Annot");
    public static final h70 G0 = new h70("CalGray");
    public static final h70 G1 = new h70("Count");
    public static final h70 G2 = new h70("Document");
    public static final h70 G3 = new h70("Fields");
    public static final h70 G4 = new h70("GoToE");
    public static final h70 G5 = new h70("Ink");
    public static final h70 G6 = new h70("Material");
    public static final h70 G7 = new h70("OC");
    public static final h70 G8 = new h70("Perceptual");
    public static final h70 G9 = new h70("Reference");
    public static final h70 Ga = new h70("Sig");
    public static final h70 Gb = new h70("TR2");
    public static final h70 Gc = new h70("UE");
    public static final h70 Gd = new h70("Wipe");
    public static final h70 H = new h70("Annots");
    public static final h70 H0 = new h70("CalRGB");
    public static final h70 H1 = new h70("Courier");
    public static final h70 H2 = new h70("Domain");
    public static final h70 H3 = new h70("Figure");
    public static final h70 H4 = new h70("GoToR");
    public static final h70 H5 = new h70("InkList");
    public static final h70 H6 = new h70("Matrix");
    public static final h70 H7 = new h70("OCG");
    public static final h70 H8 = new h70("Perms");
    public static final h70 H9 = new h70("Registry");
    public static final h70 Ha = new h70("SigFieldLock");
    public static final h70 Hb = new h70("Text");
    public static final h70 Hc = new h70("UF");
    public static final h70 Hd = new h70("WhitePoint");
    public static final h70 I = new h70("AntiAlias");
    public static final h70 I0 = new h70("CapHeight");
    public static final h70 I1 = new h70("Courier-Bold");
    public static final h70 I2 = new h70("DOS");
    public static final h70 I3 = new h70("FileAttachment");
    public static final h70 I4 = new h70("GPTS");
    public static final h70 I5 = new h70("Instances");
    public static final h70 I6 = new h70("MacExpertEncoding");
    public static final h70 I7 = new h70("OCGs");
    public static final h70 I8 = new h70("Pg");
    public static final h70 I9 = new h70("RegistryName");
    public static final h70 Ia = new h70("SigFlags");
    public static final h70 Ib = new h70("TextAlign");
    public static final h70 Ic = new h70("UHC");
    public static final h70 Id = new h70("WKT");
    public static final h70 J = new h70("AP");
    public static final h70 J0 = new h70("Caret");
    public static final h70 J1 = new h70("Courier-Oblique");
    public static final h70 J2 = new h70("DP");
    public static final h70 J3 = new h70("Filespec");
    public static final h70 J4 = new h70("Group");
    public static final h70 J5 = new h70("ImportData");
    public static final h70 J6 = new h70("MacRomanEncoding");
    public static final h70 J7 = new h70("OCMD");
    public static final h70 J8 = new h70("PI");
    public static final h70 J9 = new h70("RelativeColorimetric");
    public static final h70 Ja = new h70("SigRef");
    public static final h70 Jb = new h70("TextDecorationColor");
    public static final h70 Jc = new h70("Underline");
    public static final h70 Jd = new h70("WP");
    public static final h70 K = new h70("App");
    public static final h70 K0 = new h70("Caption");
    public static final h70 K1 = new h70("Courier-BoldOblique");
    public static final h70 K2 = new h70("DR");
    public static final h70 K3 = new h70("Filter");
    public static final h70 K4 = new h70("GTS_PDFA1");
    public static final h70 K5 = new h70("Intent");
    public static final h70 K6 = new h70("Marked");
    public static final h70 K7 = new h70("OCProperties");
    public static final h70 K8 = new h70("PickTrayByPDFSize");
    public static final h70 K9 = new h70("Rendition");
    public static final h70 Ka = new h70("Simplex");
    public static final h70 Kb = new h70("TextDecorationThickness");
    public static final h70 Kc = new h70("Unix");
    public static final h70 Kd = new h70("WS");
    public static final h70 L = new h70("AppDefault");
    public static final h70 L0 = new h70("Catalog");
    public static final h70 L1 = new h70("CreationDate");
    public static final h70 L2 = new h70("DS");
    public static final h70 L3 = new h70("First");
    public static final h70 L4 = new h70("GTS_PDFX");
    public static final h70 L5 = new h70("Interpolate");
    public static final h70 L6 = new h70("MarkInfo");
    public static final h70 L7 = new h70("OCSP");
    public static final h70 L8 = new h70("PieceInfo");
    public static final h70 L9 = new h70("Repeat");
    public static final h70 La = new h70("SinglePage");
    public static final h70 Lb = new h70("TextDecorationType");
    public static final h70 Lc = new h70("UpperAlpha");
    public static final h70 Ld = new h70("WT");
    public static final h70 M = new h70("Art");
    public static final h70 M0 = new h70("Category");
    public static final h70 M1 = new h70("Creator");
    public static final h70 M2 = new h70("DSS");
    public static final h70 M3 = new h70("FirstChar");
    public static final h70 M4 = new h70("GTS_PDFXVersion");
    public static final h70 M5 = new h70("IsMap");
    public static final h70 M6 = new h70("Mask");
    public static final h70 M7 = new h70("OCSPs");
    public static final h70 M8 = new h70("PlayCount");
    public static final h70 M9 = new h70("ResetForm");
    public static final h70 Ma = new h70("Size");
    public static final h70 Mb = new h70("TextIndent");
    public static final h70 Mc = new h70("UpperRoman");
    public static final h70 Md = new h70("X");
    public static final h70 N = new h70("ArtBox");
    public static final h70 N0 = new h70("cb");
    public static final h70 N1 = new h70("CreatorInfo");
    public static final h70 N2 = new h70("Dur");
    public static final h70 N3 = new h70("FirstPage");
    public static final h70 N4 = new h70("H");
    public static final h70 N5 = new h70("IRT");
    public static final h70 N6 = new h70("max");
    public static final h70 N7 = new h70("OE");
    public static final h70 N8 = new h70("PO");
    public static final h70 N9 = new h70("Resources");
    public static final h70 Na = new h70("SMask");
    public static final h70 Nb = new h70("TFoot");
    public static final h70 Nc = new h70("UR");
    public static final h70 Nd = new h70("XA");
    public static final h70 O = new h70("Artifact");
    public static final h70 O0 = new h70("CCITTFaxDecode");
    public static final h70 O1 = new h70("CRL");
    public static final h70 O2 = new h70("Duplex");
    public static final h70 O3 = new h70("Fit");
    public static final h70 O4 = new h70("H1");
    public static final h70 O5 = new h70("ItalicAngle");
    public static final h70 O6 = new h70("Max");
    public static final h70 O7 = new h70("Off");
    public static final h70 O8 = new h70("Polygon");
    public static final h70 O9 = new h70("Requirements");
    public static final h70 Oa = new h70("SMaskInData");
    public static final h70 Ob = new h70("TH");
    public static final h70 Oc = new h70("UR3");
    public static final h70 Od = new h70("XD");
    public static final h70 P = new h70("Ascent");
    public static final h70 P0 = new h70("Center");
    public static final h70 P1 = new h70("CRLs");
    public static final h70 P2 = new h70("DuplexFlipShortEdge");
    public static final h70 P3 = new h70("FitH");
    public static final h70 P4 = new h70("H2");
    public static final h70 P5 = new h70("ITXT");
    public static final h70 P6 = new h70("MaxLen");
    public static final h70 P7 = new h70("OFF");
    public static final h70 P8 = new h70("PolyLine");
    public static final h70 P9 = new h70("ReversedChars");
    public static final h70 Pa = new h70("Sort");
    public static final h70 Pb = new h70("THead");
    public static final h70 Pc = new h70("URI");
    public static final h70 Pd = new h70("XFA");
    public static final h70 Q = new h70("AS");
    public static final h70 Q0 = new h70("CenterWindow");
    public static final h70 Q1 = new h70("CropBox");
    public static final h70 Q2 = new h70("DuplexFlipLongEdge");
    public static final h70 Q3 = new h70("FitV");
    public static final h70 Q4 = new h70("H3");
    public static final h70 Q5 = new h70("IX");
    public static final h70 Q6 = new h70("MediaBox");
    public static final h70 Q7 = new h70("ON");
    public static final h70 Q8 = new h70("Popup");
    public static final h70 Q9 = new h70("RI");
    public static final h70 Qa = new h70("Sound");
    public static final h70 Qb = new h70("Thumb");
    public static final h70 Qc = new h70("URL");
    public static final h70 Qd = new h70("XML");
    public static final h70 R = new h70("ASCII85Decode");
    public static final h70 R0 = new h70("Cert");
    public static final h70 R1 = new h70("Crypt");
    public static final h70 R2 = new h70("DV");
    public static final h70 R3 = new h70("FitR");
    public static final h70 R4 = new h70("H4");
    public static final h70 R5 = new h70("JavaScript");
    public static final h70 R6 = new h70("MCID");
    public static final h70 R7 = new h70("OneColumn");
    public static final h70 R8 = new h70("Position");
    public static final h70 R9 = new h70("RichMedia");
    public static final h70 Ra = new h70("SpaceAfter");
    public static final h70 Rb = new h70("Threads");
    public static final h70 Rc = new h70("Usage");
    public static final h70 Rd = new h70("XObject");
    public static final h70 S = new h70("ASCIIHexDecode");
    public static final h70 S0 = new h70("Certs");
    public static final h70 S1 = new h70("CS");
    public static final h70 S2 = new h70("DW");
    public static final h70 S3 = new h70("FitB");
    public static final h70 S4 = new h70("H5");
    public static final h70 S5 = new h70("JBIG2Decode");
    public static final h70 S6 = new h70("MCR");
    public static final h70 S7 = new h70("Open");
    public static final h70 S8 = new h70("Predictor");
    public static final h70 S9 = new h70("RichMediaActivation");
    public static final h70 Sa = new h70("SpaceBefore");
    public static final h70 Sb = new h70("TI");
    public static final h70 Sc = new h70("UseAttachments");
    public static final h70 Sd = new h70("XPTS");
    public static final h70 T = new h70("Asset");
    public static final h70 T0 = new h70("CF");
    public static final h70 T1 = new h70("CuePoint");
    public static final h70 T2 = new h70("E");
    public static final h70 T3 = new h70("FitBH");
    public static final h70 T4 = new h70("H6");
    public static final h70 T5 = new h70("JBIG2Globals");
    public static final h70 T6 = new h70("Measure");
    public static final h70 T7 = new h70("OpenAction");
    public static final h70 T8 = new h70("Preferred");
    public static final h70 T9 = new h70("RichMediaAnimation");
    public static final h70 Ta = new h70("Span");
    public static final h70 Tb = new h70("Time");
    public static final h70 Tc = new h70("UseNone");
    public static final h70 Td = new h70("XRef");
    public static final h70 U = new h70("Assets");
    public static final h70 U0 = new h70("CFM");
    public static final h70 U1 = new h70("CuePoints");
    public static final h70 U2 = new h70("EarlyChange");
    public static final h70 U3 = new h70("FitBV");
    public static final h70 U4 = new h70("HalftoneName");
    public static final h70 U5 = new h70("JPXDecode");
    public static final h70 U6 = new h70("Metadata");
    public static final h70 U7 = new h70("OP");
    public static final h70 U8 = new h70("Presentation");
    public static final h70 U9 = new h70("RichMediaCommand");
    public static final h70 Ua = new h70("Speed");
    public static final h70 Ub = new h70("TilingType");
    public static final h70 Uc = new h70("UseOC");
    public static final h70 Ud = new h70("XRefStm");
    public static final h70 V = new h70("Attached");
    public static final h70 V0 = new h70("Ch");
    public static final h70 V1 = new h70("CYX");
    public static final h70 V2 = new h70("EF");
    public static final h70 V3 = new h70("FitWindow");
    public static final h70 V4 = new h70("HalftoneType");
    public static final h70 V5 = new h70("JS");
    public static final h70 V6 = new h70("min");
    public static final h70 V7 = new h70("op");
    public static final h70 V8 = new h70("PreserveRB");
    public static final h70 V9 = new h70("RichMediaConfiguration");
    public static final h70 Va = new h70("Split");
    public static final h70 Vb = new h70("Times-Roman");
    public static final h70 Vc = new h70("UseOutlines");
    public static final h70 Vd = new h70("XStep");
    public static final h70 W = new h70("AuthEvent");
    public static final h70 W0 = new h70("CharProcs");
    public static final h70 W1 = new h70("D");
    public static final h70 W2 = new h70("EFF");
    public static final h70 W3 = new h70("Fl");
    public static final h70 W4 = new h70("HAlign");
    public static final h70 W5 = new h70("Justify");
    public static final h70 W6 = new h70("Min");
    public static final h70 W7 = new h70("OPI");
    public static final h70 W8 = new h70("PresSteps");
    public static final h70 W9 = new h70("RichMediaContent");
    public static final h70 Wa = new h70("Square");
    public static final h70 Wb = new h70("Times-Bold");
    public static final h70 Wc = new h70("User");
    public static final h70 Wd = new h70("XYZ");
    public static final h70 X = new h70("Author");
    public static final h70 X0 = new h70("CheckSum");
    public static final h70 X1 = new h70("DA");
    public static final h70 X2 = new h70("EFOpen");
    public static final h70 X3 = new h70("Flags");
    public static final h70 X4 = new h70("Headers");
    public static final h70 X5 = new h70("K");
    public static final h70 X6 = new h70("MK");
    public static final h70 X7 = new h70("OPM");
    public static final h70 X8 = new h70("Prev");
    public static final h70 X9 = new h70("RichMediaDeactivation");
    public static final h70 Xa = new h70("Squiggly");
    public static final h70 Xb = new h70("Times-Italic");
    public static final h70 Xc = new h70("UserProperties");
    public static final h70 Xd = new h70("YStep");
    public static final h70 Y = new h70("B");
    public static final h70 Y0 = new h70("CI");
    public static final h70 Y1 = new h70("Data");
    public static final h70 Y2 = new h70("Embedded");
    public static final h70 Y3 = new h70("Flash");
    public static final h70 Y4 = new h70("Height");
    public static final h70 Y5 = new h70("Keywords");
    public static final h70 Y6 = new h70("MMType1");
    public static final h70 Y7 = new h70("Opt");
    public static final h70 Y8 = new h70("PrevPage");
    public static final h70 Y9 = new h70("RichMediaExecute");
    public static final h70 Ya = new h70("SS");
    public static final h70 Yb = new h70("Times-BoldItalic");
    public static final h70 Yc = new h70("UserUnit");
    public static final h70 Yd = new h70("ZaDb");
    public static final h70 Z = new h70("Background");
    public static final h70 Z0 = new h70("CIDFontType0");
    public static final h70 Z1 = new h70("DC");
    public static final h70 Z2 = new h70("EmbeddedFile");
    public static final h70 Z3 = new h70("FlashVars");
    public static final h70 Z4 = new h70("Helv");
    public static final h70 Z5 = new h70("Kids");
    public static final h70 Z6 = new h70("ModDate");
    public static final h70 Z7 = new h70("Or");
    public static final h70 Z8 = new h70("Print");
    public static final h70 Z9 = new h70("RichMediaInstance");
    public static final h70 Za = new h70("St");
    public static final h70 Zb = new h70("Title");
    public static final h70 Zc = new h70("UseThumbs");
    public static final h70 Zd = new h70("ZapfDingbats");
    public static final h70 a = new h70("3D");

    /* renamed from: a  reason: collision with other field name */
    public static Map<String, h70> f3150a;
    public static final h70 a0 = new h70("BackgroundColor");
    public static final h70 a1 = new h70("CIDFontType2");
    public static final h70 a2 = new h70("DCS");
    public static final h70 a3 = new h70("EmbeddedFiles");
    public static final h70 a4 = new h70("FlateDecode");
    public static final h70 a5 = new h70("Helvetica");
    public static final h70 a6 = new h70("L");
    public static final h70 a7 = new h70("Movie");
    public static final h70 a8 = new h70("Order");
    public static final h70 a9 = new h70("PrintArea");
    public static final h70 aa = new h70("RichMediaParams");
    public static final h70 ab = new h70("Stamp");
    public static final h70 ac = new h70("TK");
    public static final h70 ad = new h70("utf_8");
    public static final h70 ae = new h70("Zoom");
    public static final h70 b = new h70("A");
    public static final h70 b0 = new h70("BaseEncoding");
    public static final h70 b1 = new h70("CIDSet");
    public static final h70 b2 = new h70("DCTDecode");
    public static final h70 b3 = new h70("Encode");
    public static final h70 b4 = new h70("Fo");
    public static final h70 b5 = new h70("Helvetica-Bold");
    public static final h70 b6 = new h70("L2R");
    public static final h70 b7 = new h70("N");
    public static final h70 b8 = new h70("Ordering");
    public static final h70 b9 = new h70("PrintClip");
    public static final h70 ba = new h70("RichMediaPosition");
    public static final h70 bb = new h70("Status");
    public static final h70 bc = new h70("TM");
    public static final h70 bd = new h70("V");
    public static final h70 c = new h70("A85");
    public static final h70 c0 = new h70("BaseFont");
    public static final h70 c1 = new h70("CIDSystemInfo");
    public static final h70 c2 = new h70("Decimal");
    public static final h70 c3 = new h70("EncodedByteAlign");
    public static final h70 c4 = new h70("Font");
    public static final h70 c5 = new h70("Helvetica-Oblique");
    public static final h70 c6 = new h70("Lab");
    public static final h70 c7 = new h70("n0");
    public static final h70 c8 = new h70("Org");
    public static final h70 c9 = new h70("PrinterMark");
    public static final h70 ca = new h70("RichMediaPresentation");
    public static final h70 cb = new h70("Standard");
    public static final h70 cc = new h70("TOC");
    public static final h70 cd = new h70("V2");
    public static final h70 d = new h70("AA");
    public static final h70 d0 = new h70("BaseVersion");
    public static final h70 d1 = new h70("CIDToGIDMap");
    public static final h70 d2 = new h70("Deactivation");
    public static final h70 d3 = new h70("Encoding");
    public static final h70 d4 = new h70("FontBBox");
    public static final h70 d5 = new h70("Helvetica-BoldOblique");
    public static final h70 d6 = new h70("Lang");
    public static final h70 d7 = new h70("n1");
    public static final h70 d8 = new h70("Oscillating");
    public static final h70 d9 = new h70("PrintField");
    public static final h70 da = new h70("RichMediaSettings");
    public static final h70 db = new h70("Start");
    public static final h70 dc = new h70("TOCI");
    public static final h70 dd = new h70("VAlign");
    public static final h70 e = new h70("AbsoluteColorimetric");
    public static final h70 e0 = new h70("BBox");
    public static final h70 e1 = new h70("Circle");
    public static final h70 e2 = new h70("Decode");
    public static final h70 e3 = new h70("Encrypt");
    public static final h70 e4 = new h70("FontDescriptor");
    public static final h70 e5 = new h70("HF");
    public static final h70 e6 = new h70("Language");
    public static final h70 e7 = new h70("n2");
    public static final h70 e8 = new h70("Outlines");
    public static final h70 e9 = new h70("PrintPageRange");
    public static final h70 ea = new h70("RichMediaWindow");
    public static final h70 eb = new h70("StartIndent");
    public static final h70 ec = new h70("Toggle");
    public static final h70 ed = new h70("VE");
    public static final h70 f = new h70("AC");
    public static final h70 f0 = new h70("BC");
    public static final h70 f1 = new h70("ClassMap");
    public static final h70 f2 = new h70("DecodeParms");
    public static final h70 f3 = new h70("EncryptMetadata");
    public static final h70 f4 = new h70("FontFamily");
    public static final h70 f5 = new h70("Hid");
    public static final h70 f6 = new h70("Last");
    public static final h70 f7 = new h70("n3");
    public static final h70 f8 = new h70("OutputCondition");
    public static final h70 f9 = new h70("PrintScaling");
    public static final h70 fa = new h70("RL");
    public static final h70 fb = new h70("State");
    public static final h70 fc = new h70("Toolbar");
    public static final h70 fd = new h70("VeriSign.PPKVS");
    public static final h70 g = new h70("AcroForm");
    public static final h70 g0 = new h70("BG");
    public static final h70 g1 = new h70("Cloud");
    public static final h70 g2 = new h70("Default");
    public static final h70 g3 = new h70("End");
    public static final h70 g4 = new h70("FontFile");
    public static final h70 g5 = new h70("Hide");
    public static final h70 g6 = new h70("LastChar");
    public static final h70 g7 = new h70("n4");
    public static final h70 g8 = new h70("OutputConditionIdentifier");
    public static final h70 g9 = new h70("PrintState");
    public static final h70 ga = new h70("Role");
    public static final h70 gb = new h70("StdCF");
    public static final h70 gc = new h70("ToUnicode");
    public static final h70 gd = new h70("Version");
    public static final h70 h = new h70("Action");
    public static final h70 h0 = new h70("BibEntry");
    public static final h70 h1 = new h70("CMD");
    public static final h70 h2 = new h70("DefaultCryptFilter");
    public static final h70 h3 = new h70("EndIndent");
    public static final h70 h4 = new h70("FontFile2");
    public static final h70 h5 = new h70("HideMenubar");
    public static final h70 h6 = new h70("LastPage");
    public static final h70 h7 = new h70("Name");
    public static final h70 h8 = new h70("OutputIntent");
    public static final h70 h9 = new h70("Private");
    public static final h70 ha = new h70("RO");
    public static final h70 hb = new h70("StemV");
    public static final h70 hc = new h70("TP");
    public static final h70 hd = new h70("Vertices");
    public static final h70 i = new h70("Activation");
    public static final h70 i0 = new h70("BigFive");
    public static final h70 i1 = new h70("CO");
    public static final h70 i2 = new h70("DefaultCMYK");
    public static final h70 i3 = new h70("EndOfBlock");
    public static final h70 i4 = new h70("FontFile3");
    public static final h70 i5 = new h70("HideToolbar");
    public static final h70 i6 = new h70("Launch");
    public static final h70 i7 = new h70("Named");
    public static final h70 i8 = new h70("OutputIntents");
    public static final h70 i9 = new h70("ProcSet");
    public static final h70 ia = new h70("RoleMap");
    public static final h70 ib = new h70("StmF");
    public static final h70 ic = new h70("TR");
    public static final h70 id = new h70("Video");
    public static final h70 j = new h70("ADBE");
    public static final h70 j0 = new h70("Binding");
    public static final h70 j1 = new h70("Code");
    public static final h70 j2 = new h70("DefaultGray");
    public static final h70 j3 = new h70("EndOfLine");
    public static final h70 j4 = new h70("FontMatrix");
    public static final h70 j5 = new h70("HideWindowUI");
    public static final h70 j6 = new h70("Layout");
    public static final h70 j7 = new h70("Names");
    public static final h70 j8 = new h70("OverlayText");
    public static final h70 j9 = new h70("Producer");
    public static final h70 ja = new h70("Root");
    public static final h70 jb = new h70("StrF");
    public static final h70 jc = new h70("Trans");
    public static final h70 jd = new h70("View");
    public static final h70 k = new h70("ActualText");
    public static final h70 k0 = new h70("BindingMaterialName");
    public static final h70 k1 = new h70("Color");
    public static final h70 k2 = new h70("DefaultRGB");
    public static final h70 k3 = new h70("EPSG");
    public static final h70 k4 = new h70("FontName");
    public static final h70 k5 = new h70("Highlight");
    public static final h70 k6 = new h70("Lbl");
    public static final h70 k7 = new h70("Navigation");
    public static final h70 k8 = new h70("P");
    public static final h70 k9 = new h70("PROJCS");
    public static final h70 ka = new h70("Rotate");
    public static final h70 kb = new h70("StrikeOut");
    public static final h70 kc = new h70("TransformParams");
    public static final h70 kd = new h70("Views");
    public static final h70 l = new h70("adbe.pkcs7.detached");
    public static final h70 l0 = new h70("BitsPerComponent");
    public static final h70 l1 = new h70("Colorants");
    public static final h70 l2 = new h70("Desc");
    public static final h70 l3 = new h70("ESIC");
    public static final h70 l4 = new h70("FontWeight");
    public static final h70 l5 = new h70("HOffset");
    public static final h70 l6 = new h70("LBody");
    public static final h70 l7 = new h70("NavigationPane");
    public static final h70 l8 = new h70("Page");
    public static final h70 l9 = new h70("Prop_Build");
    public static final h70 la = new h70("Row");
    public static final h70 lb = new h70("StructElem");
    public static final h70 lc = new h70("TransformMethod");
    public static final h70 ld = new h70("ViewArea");
    public static final h70 m = new h70("adbe.pkcs7.s4");
    public static final h70 m0 = new h70("BitsPerSample");
    public static final h70 m1 = new h70("Colors");
    public static final h70 m2 = new h70("DescendantFonts");
    public static final h70 m3 = new h70("ETSI.CAdES.detached");
    public static final h70 m4 = new h70("Foreground");
    public static final h70 m5 = new h70("HT");
    public static final h70 m6 = new h70("Length");
    public static final h70 m7 = new h70("NChannel");
    public static final h70 m8 = new h70("PageElement");
    public static final h70 m9 = new h70("Properties");
    public static final h70 ma = new h70("Rows");
    public static final h70 mb = new h70("StructParent");
    public static final h70 mc = new h70("Transparency");
    public static final h70 md = new h70("ViewClip");
    public static final h70 n = new h70("adbe.pkcs7.s5");
    public static final h70 n0 = new h70("Bl");
    public static final h70 n1 = new h70("ColorSpace");
    public static final h70 n2 = new h70("Descent");
    public static final h70 n3 = new h70("ETSI.RFC3161");
    public static final h70 n4 = new h70("Form");
    public static final h70 n5 = new h70("HTP");
    public static final h70 n6 = new h70("Length1");
    public static final h70 n7 = new h70("Near");
    public static final h70 n8 = new h70("PageLabels");
    public static final h70 n9 = new h70("PS");
    public static final h70 na = new h70("RowSpan");
    public static final h70 nb = new h70("StructParents");
    public static final h70 nc = new h70("Transparent");
    public static final h70 nd = new h70("ViewerPreferences");
    public static final h70 o = new h70("adbe.pkcs7.sha1");
    public static final h70 o0 = new h70("BlackIs1");
    public static final h70 o1 = new h70("ColorTransform");
    public static final h70 o2 = new h70("Dest");
    public static final h70 o3 = new h70("Exclude");
    public static final h70 o4 = new h70("FormType");
    public static final h70 o5 = new h70("I");
    public static final h70 o6 = new h70("LI");
    public static final h70 o7 = new h70("NeedAppearances");
    public static final h70 o8 = new h70("PageLayout");
    public static final h70 o9 = new h70("PtData");
    public static final h70 oa = new h70("RP");
    public static final h70 ob = new h70("StructTreeRoot");
    public static final h70 oc = new h70("TrapNet");
    public static final h70 od = new h70("Viewport");
    public static final h70 p = new h70("adbe.x509.rsa_sha1");
    public static final h70 p0 = new h70("BlackPoint");
    public static final h70 p1 = new h70("Collection");
    public static final h70 p2 = new h70("DestOutputProfile");
    public static final h70 p3 = new h70("Extend");
    public static final h70 p4 = new h70("Formula");
    public static final h70 p5 = new h70("IC");
    public static final h70 p6 = new h70("Limits");
    public static final h70 p7 = new h70("NeedsRendering");
    public static final h70 p8 = new h70("PageMode");
    public static final h70 p9 = new h70("Adobe.PubSec");
    public static final h70 pa = new h70("RT");
    public static final h70 pb = new h70("Style");
    public static final h70 pc = new h70("Trapped");
    public static final h70 pd = new h70("ViewState");
    public static final h70 q = new h70("Adobe.PPKLite");
    public static final h70 q0 = new h70("BlockQuote");
    public static final h70 q1 = new h70("CollectionField");
    public static final h70 q2 = new h70("Dests");
    public static final h70 q3 = new h70("Extensions");
    public static final h70 q4 = new h70("FreeText");
    public static final h70 q5 = new h70("ICCBased");
    public static final h70 q6 = new h70("Line");
    public static final h70 q7 = new h70("NewWindow");
    public static final h70 q8 = new h70("Pages");
    public static final h70 q9 = new h70("PV");
    public static final h70 qa = new h70("Ruby");
    public static final h70 qb = new h70("SubFilter");
    public static final h70 qc = new h70("TrimBox");
    public static final h70 qd = new h70("VisiblePages");
    public static final h70 r = new h70("Adobe.PPKMS");
    public static final h70 r0 = new h70("BleedBox");
    public static final h70 r1 = new h70("CollectionItem");
    public static final h70 r2 = new h70("DeviceGray");
    public static final h70 r3 = new h70("ExtensionLevel");
    public static final h70 r4 = new h70("FRM");
    public static final h70 r5 = new h70("ID");
    public static final h70 r6 = new h70("Linear");
    public static final h70 r7 = new h70("Next");
    public static final h70 r8 = new h70("PaintType");
    public static final h70 r9 = new h70("Q");
    public static final h70 ra = new h70("RunLengthDecode");
    public static final h70 rb = new h70("Subject");
    public static final h70 rc = new h70("TrueType");
    public static final h70 rd = new h70("VOffset");
    public static final h70 s = new h70("AESV2");
    public static final h70 s0 = new h70("Blinds");
    public static final h70 s1 = new h70("CollectionSchema");
    public static final h70 s2 = new h70("DeviceRGB");
    public static final h70 s3 = new h70("ExtGState");
    public static final h70 s4 = new h70("FS");
    public static final h70 s5 = new h70("Identity");
    public static final h70 s6 = new h70("LineHeight");
    public static final h70 s7 = new h70("NextPage");
    public static final h70 s8 = new h70("Panose");
    public static final h70 s9 = new h70("QuadPoints");
    public static final h70 sa = new h70("RV");
    public static final h70 sb = new h70("SubmitForm");
    public static final h70 sc = new h70("TS");
    public static final h70 sd = new h70("VP");
    public static final h70 t = new h70("AESV3");
    public static final h70 t0 = new h70("BM");
    public static final h70 t1 = new h70("CollectionSort");
    public static final h70 t2 = new h70("DeviceCMYK");
    public static final h70 t3 = new h70("Export");
    public static final h70 t4 = new h70("FT");
    public static final h70 t5 = new h70("IDTree");
    public static final h70 t6 = new h70("Link");
    public static final h70 t7 = new h70("NM");
    public static final h70 t8 = new h70("Params");
    public static final h70 t9 = new h70("Quote");
    public static final h70 ta = new h70("S");
    public static final h70 tb = new h70("Subtype");
    public static final h70 tc = new h70("Ttl");
    public static final h70 td = new h70("VRI");
    public static final h70 u = new h70("AF");
    public static final h70 u0 = new h70("Border");
    public static final h70 u1 = new h70("CollectionSubitem");
    public static final h70 u2 = new h70("DeviceN");
    public static final h70 u3 = new h70("ExportState");
    public static final h70 u4 = new h70("FullScreen");
    public static final h70 u5 = new h70("IF");
    public static final h70 u6 = new h70("List");
    public static final h70 u7 = new h70("None");
    public static final h70 u8 = new h70("Parent");
    public static final h70 u9 = new h70("R");
    public static final h70 ua = new h70("Saturation");
    public static final h70 ub = new h70("Summary");
    public static final h70 uc = new h70("TU");
    public static final h70 ud = new h70("W");
    public static final h70 v = new h70("AFRelationship");
    public static final h70 v0 = new h70("Both");
    public static final h70 v1 = new h70("ColSpan");
    public static final h70 v2 = new h70("Di");
    public static final h70 v3 = new h70("Event");
    public static final h70 v4 = new h70("Function");
    public static final h70 v5 = new h70("IM");
    public static final h70 v6 = new h70("ListMode");
    public static final h70 v7 = new h70("NonFullScreenPageMode");
    public static final h70 v8 = new h70("ParentTree");
    public static final h70 v9 = new h70("R2L");
    public static final h70 va = new h70("Schema");
    public static final h70 vb = new h70("Supplement");
    public static final h70 vc = new h70("tv");
    public static final h70 vd = new h70("W2");
    public static final h70 w = new h70("AHx");
    public static final h70 w0 = new h70("Bounds");
    public static final h70 w1 = new h70("Column");
    public static final h70 w2 = new h70("Differences");
    public static final h70 w3 = new h70("F");
    public static final h70 w4 = new h70("Functions");
    public static final h70 w5 = new h70("Image");
    public static final h70 w6 = new h70("ListNumbering");
    public static final h70 w7 = new h70("NonStruct");
    public static final h70 w8 = new h70("ParentTreeNextKey");
    public static final h70 w9 = new h70(HttpHeaders.RANGE);
    public static final h70 wa = new h70("Scope");
    public static final h70 wb = new h70("SV");
    public static final h70 wc = new h70("TwoColumnLeft");
    public static final h70 wd = new h70("Warichu");
    public static final h70 x = new h70("AIS");
    public static final h70 x0 = new h70("Box");
    public static final h70 x1 = new h70("Columns");
    public static final h70 x2 = new h70("Dissolve");
    public static final h70 x3 = new h70("Far");
    public static final h70 x4 = new h70("FunctionType");
    public static final h70 x5 = new h70("ImageB");
    public static final h70 x6 = new h70(HttpHeaders.LOCATION);
    public static final h70 x7 = new h70("Not");
    public static final h70 x8 = new h70("Part");
    public static final h70 x9 = new h70("RB");
    public static final h70 xa = new h70("Screen");
    public static final h70 xb = new h70("SW");
    public static final h70 xc = new h70("TwoColumnRight");
    public static final h70 xd = new h70("Watermark");
    public static final h70 y = new h70("All");
    public static final h70 y0 = new h70("BS");
    public static final h70 y1 = new h70("Condition");
    public static final h70 y2 = new h70("Direction");
    public static final h70 y3 = new h70("FB");
    public static final h70 y4 = new h70("Gamma");
    public static final h70 y5 = new h70("ImageC");
    public static final h70 y6 = new h70("Lock");
    public static final h70 y7 = new h70("Note");
    public static final h70 y8 = new h70("PassContextClick");
    public static final h70 y9 = new h70("rb");
    public static final h70 ya = new h70("Scripts");
    public static final h70 yb = new h70("Symbol");
    public static final h70 yc = new h70("TwoPageLeft");
    public static final h70 yd = new h70("WC");
    public static final h70 z = new h70("AllPages");
    public static final h70 z0 = new h70("Btn");
    public static final h70 z1 = new h70("Configs");
    public static final h70 z2 = new h70("DisplayDocTitle");
    public static final h70 z3 = new h70("FD");
    public static final h70 z4 = new h70("GBK");
    public static final h70 z5 = new h70("ImageI");
    public static final h70 z6 = new h70("Locked");
    public static final h70 z7 = new h70("NumberFormat");
    public static final h70 z8 = new h70("Pattern");
    public static final h70 z9 = new h70("RBGroups");
    public static final h70 za = new h70("Sect");
    public static final h70 zb = new h70("T");
    public static final h70 zc = new h70("TwoPageRight");
    public static final h70 zd = new h70("Widget");

    /* renamed from: b  reason: collision with other field name */
    private int f3151b;

    static {
        Field[] fields = h70.class.getDeclaredFields();
        f3150a = new HashMap(fields.length);
        int fldIdx = 0;
        while (fldIdx < fields.length) {
            try {
                Field curFld = fields[fldIdx];
                if ((curFld.getModifiers() & 25) == 25 && curFld.getType().equals(h70.class)) {
                    h70 name = (h70) curFld.get((Object) null);
                    f3150a.put(I(name.toString()), name);
                }
                fldIdx++;
            } catch (Exception e10) {
                e10.printStackTrace();
                return;
            }
        }
    }

    public h70(String name) {
        this(name, true);
    }

    public h70(String name, boolean lengthCheck) {
        super(4);
        this.f3151b = 0;
        int length = name.length();
        if (!lengthCheck || length <= 127) {
            this.f4495a = J(name);
        } else {
            throw new IllegalArgumentException(i10.b("the.name.1.is.too.long.2.characters", name, String.valueOf(length)));
        }
    }

    /* renamed from: H */
    public int compareTo(h70 name) {
        byte[] myBytes = this.f4495a;
        byte[] objBytes = name.f4495a;
        int len = Math.min(myBytes.length, objBytes.length);
        for (int i10 = 0; i10 < len; i10++) {
            if (myBytes[i10] > objBytes[i10]) {
                return 1;
            }
            if (myBytes[i10] < objBytes[i10]) {
                return -1;
            }
        }
        if (myBytes.length < objBytes.length) {
            return -1;
        }
        if (myBytes.length > objBytes.length) {
            return 1;
        }
        return 0;
    }

    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof h70) || compareTo((h70) obj) != 0) {
            return false;
        }
        return true;
    }

    public int hashCode() {
        int h10 = this.f3151b;
        if (h10 == 0) {
            int ptr = 0;
            int len = this.f4495a.length;
            int i10 = 0;
            while (i10 < len) {
                h10 = (h10 * 31) + (this.f4495a[ptr] & 255);
                i10++;
                ptr++;
            }
            this.f3151b = h10;
        }
        return h10;
    }

    public static byte[] J(String name) {
        int length = name.length();
        w6 buf = new w6(length + 20);
        buf.f('/');
        char[] chars = name.toCharArray();
        for (int k10 = 0; k10 < length; k10++) {
            char c10 = (char) (chars[k10] & 255);
            switch (c10) {
                case ' ':
                case '#':
                case '%':
                case '(':
                case ')':
                case '/':
                case '<':
                case '>':
                case '[':
                case ']':
                case '{':
                case '}':
                    buf.f('#');
                    buf.J(Integer.toString(c10, 16));
                    break;
                default:
                    if (c10 >= ' ' && c10 <= '~') {
                        buf.f(c10);
                        break;
                    } else {
                        buf.f('#');
                        if (c10 < 16) {
                            buf.f('0');
                        }
                        buf.J(Integer.toString(c10, 16));
                        break;
                    }
                    break;
            }
        }
        return buf.c0();
    }

    public static String I(String name) {
        StringBuffer buf = new StringBuffer();
        try {
            int len = name.length();
            int k10 = 1;
            while (k10 < len) {
                char c10 = name.charAt(k10);
                if (c10 == '#') {
                    c10 = (char) ((a.c(name.charAt(k10 + 1)) << 4) + a.c(name.charAt(k10 + 2)));
                    k10 += 2;
                }
                buf.append(c10);
                k10++;
            }
        } catch (IndexOutOfBoundsException e10) {
        }
        return buf.toString();
    }
}
