package defpackage;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/* renamed from: oi  reason: default package */
abstract class oi {
    static <B extends a6<B>> String c(B path) {
        StringBuilder result = new StringBuilder();
        int length = path.n();
        for (int i = 0; i < length; i++) {
            if (result.length() > 0) {
                e(result);
            }
            d(path.i(i), result);
        }
        e(result);
        return result.toString();
    }

    private static void d(String segment, StringBuilder result) {
        int length = segment.length();
        for (int i = 0; i < length; i++) {
            char c = segment.charAt(i);
            switch (c) {
                case 0:
                    result.append(1);
                    result.append(16);
                    break;
                case 1:
                    result.append(1);
                    result.append(17);
                    break;
                default:
                    result.append(c);
                    break;
            }
        }
    }

    private static void e(StringBuilder result) {
        result.append(1);
        result.append(1);
    }

    static me0 b(String path) {
        return me0.s(a(path));
    }

    private static List<String> a(String path) {
        String segment;
        int length = path.length();
        n4.d(length >= 2, "Invalid path \"%s\"", path);
        if (length == 2) {
            n4.d(path.charAt(0) == 1 && path.charAt(1) == 1, "Non-empty path \"%s\" had length 2", path);
            return Collections.emptyList();
        }
        int lastReasonableEscapeIndex = path.length() - 2;
        List<String> segments = new ArrayList<>();
        StringBuilder segmentBuilder = new StringBuilder();
        int start = 0;
        while (start < length) {
            int end = path.indexOf(1, start);
            if (end < 0 || end > lastReasonableEscapeIndex) {
                throw new IllegalArgumentException("Invalid encoded resource path: \"" + path + "\"");
            }
            switch (path.charAt(end + 1)) {
                case 1:
                    String currentPiece = path.substring(start, end);
                    if (segmentBuilder.length() == 0) {
                        segment = currentPiece;
                    } else {
                        segmentBuilder.append(currentPiece);
                        segment = segmentBuilder.toString();
                        segmentBuilder.setLength(0);
                    }
                    segments.add(segment);
                    break;
                case 16:
                    segmentBuilder.append(path.substring(start, end));
                    segmentBuilder.append(0);
                    break;
                case 17:
                    segmentBuilder.append(path.substring(start, end + 1));
                    break;
                default:
                    throw new IllegalArgumentException("Invalid encoded resource path: \"" + path + "\"");
            }
            start = end + 2;
        }
        return segments;
    }

    static String f(String path) {
        StringBuilder result = new StringBuilder(path);
        boolean z = true;
        int pos = result.length() - 1;
        char c = result.charAt(pos);
        if (c != 1) {
            z = false;
        }
        n4.d(z, "successor may only operate on paths generated by encode", new Object[0]);
        result.setCharAt(pos, (char) (c + 1));
        return result.toString();
    }
}
