// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
const hasSupabaseEnv = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

const url = SUPABASE_URL ?? 'http://127.0.0.1:54321';
const key = SUPABASE_PUBLISHABLE_KEY ?? 'public-anon-key';

if (!hasSupabaseEnv) {
  console.warn('Supabase env vars missing; using fallback client to allow builds to succeed.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(url, key, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: hasSupabaseEnv,
    autoRefreshToken: hasSupabaseEnv,
  }
});
